#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Update path
path=(
  ~/bin
  ~/bin/*/
  ~/perl5/perlbrew/bin
  /usr/local/share/python3
  /usr/local/share/python
  $path
)
source ~/perl5/perlbrew/etc/bashrc

function nopassword {
    cat ~/.ssh/id_rsa.pub | ssh $1 "mkdir -p ~/.ssh && cat - >> ~/.ssh/authorized_keys"
}

function forgethost {
    sed -i "${1}d" ~/.ssh/known_hosts
}

function swordfish {
    openssl rand -base64 201 | perl -ne 's/\n//g; print $_;' | head -c $1 | pbcopy
}
