#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

autoload -U zmv

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Update path
path=(
  ~/bin
  ~/bin/*
  ~/perl5/perlbrew/bin
  /usr/local/bin
  /usr/local/share/npm/bin
  $path
)

fpath=(
  ~/.zsh/completion
  /usr/local/share/zsh-completions
  $fpath
)
compinit

typeset -A SF_PERL
typeset -T SF_PERL_PATH SF_PERL
SF_PERL+=(`print ~/Sourcefire/perl/*`)

export RBENV_ROOT=/usr/local/var/rbenv
export SBT_OPTS=-XX:MaxPermSize=512m
export PERL5LIB=~/Sourcefire/sf-mockup/lib
export CVSROOT=esturcke@scm.sfeng.sourcefire.com:/usr/cvsroot

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

function nopassword {
    cat ~/.ssh/id_rsa.pub | ssh $1 "mkdir -p ~/.ssh && cat - >> ~/.ssh/authorized_keys"
}

function forgethost {
    sed -i "${1}d" ~/.ssh/known_hosts
}

function swordfish {
    openssl rand -base64 256 | perl -ne 's/\n//g; print $_;' | head -c $1 | pbcopy
}

# http://superuser.com/questions/337134/how-do-i-stop-apple-mail-from-opening-because-of-ical-appointments
alias disable-mail.app="sudo chmod 000 /Applications/Mail.app/Contents/MacOS/Mail"
alias photoshop="open -a Adobe\ Photoshop\ CS6"
alias mark="open -a Marked.app"
alias vi="vim"
alias serve="python -m SimpleHTTPServer"
source ~/perl5/perlbrew/etc/bashrc
alias sfperl="SF_PERL+=(`print ~/Sourcefire/perl/*`); PERL5LIB=$PERL5LIB:$SF_PERL_PATH"
alias ijulia="ipython notebook --profile julia"
alias colors='for code in {000..255}; do print -nP -- "%F{$code}$code %f"; [ $((${code} % 16)) -eq 15 ] && echo; done'
